# =============================================================================
# Config
# =============================================================================
# RWR-Prometheus v1.0.0
# Author: Lozaine@TamaWish
# =============================================================================

# =============================================================================
# Server
# =============================================================================

server:
  address: 127.0.0.1
  port: 9225
  metrics-path: /metrics
